### ISSUE TITLE
Writing A Read Me

### ISSUE THREAD

**Issue by slippy-idk** [slippy-idk/Smart-cashOS#8]
-Should explain the project
-Link to the contribution Guideline
-Should include some level of code standard

**Comment by aSimpson02** [comment]
hi, I would like to contribute to this if that is ok?

**Comment by slippy-idk** [comment]
Beacuse of the GUI Support this issue might not be Fixed this yet to be seen

**Comment by slippy-idk** [comment]
That is perfectly fine, I am more than happy for you to write a read me pls send any other comment if you have Questions

**Comment by aSimpson02** [comment]
Hi no worries on the response, I do have a few questions about the project before beginning a Readme:
- what is Smart-cashOS? 
- What problem does it solve?
- How can users contribute to the project? 
- How can someone install or get started with the project? 
- Any additional Information needed to be known before engaging with smart-cashOS?
- What license is the project under?

**Comment by slippy-idk** [comment]
what is Smart-cashOS?

Smart-cashOS is software that will be run on I pad systems that will replicate a Cash register with a User Account system that will keep track of statistics of employees and sales such as the software will work on tracking total amount of revenue of each day which help small business find out which days and which times of each day generate the most revenue for the business and the amount of hours on average an employee works on a register the system will be designed to be highly customizable for businesses to allow the software to be modified by a business within the software to support their business structure.
 The exact features of the software are being designed and implemented with the development cycle and for this reason the features it supports will grow with development

What problem does it solve?

While such system may exists already for larger business the idea behind this software is to help smaller business have a similar system using this software as such existing system are designed only for one business

How can users contribute to the project?
A user can contribute by looking at any active issues on the  GitHub and make their own fork of the project and begin working towards solving the issue and implementing and or fixing a bug related to the issue and creating a pull request once they believe they have managed to solve the open issue, I may begin later in the project writing more documentation including a general development overview with notes for what parts I would be most keen to have help on

How can someone install or get started with the project?
for now they can fork the project and begin development on an open issue and than submit a pull request when they believe they have managed to implement a fix of the issue or implantation of a feature the issue is open in my current branch I'm using javaFX while this will not need any extra install as all the library files will be included in the project knowledge of javaFX may be needed in order to work on any future branch based of the GUI branch if they wish to work on a issue relating to the GUI however I choose JavaFX due to its simplicity of usage and may include documentation on how to use it in future branches

Any additional Information needed to be known before engaging with smart-cashOS?

as of this time there is no extra information that is needed in order to begin engaging with Smart-cashOS
But in future this may change and in which case I will update when needed and I may make discord for contributors in the future for a more guided development

What license is the project under?

as of right now this project is not under a licence but this is a very high priority issue that is being researched and the license that will be chosen will be one that retains this project's open source nature I am willing to update any related documentation once a license has be finalised

<------->
I hope this helps your understanding of the project if you any further questions feel free to ask this project was one that was started as a personal project to test my coding skills but it seems to be developing into one that is open source that is free for anyone to contribute to for any reason which I am more than happy with and thank you for your interest

**Comment by aSimpson02** [comment]
thank you, I am currently finalising the readme file right now, apologies for the time delay

**Comment by slippy-idk** [comment]
Its no problem

**Comment by slippy-idk** [comment]
This project has been finished by @aSimpson02
